CREATE TABLE CURSO (
 Curso CHAR(4) NOT NULL,
 Nome_Curso VARCHAR(60) NOT NULL
);

ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (Curso);


CREATE TABLE DISCIPLINA (
 Disciplina CHAR(8) NOT NULL,
 Denominacao VARCHAR(60) NOT NULL,
 Nivel NUMERIC(3) NOT NULL,
 Curso CHAR(4)
);

ALTER TABLE DISCIPLINA ADD CONSTRAINT PK_DISCIPLINA PRIMARY KEY (Disciplina);


CREATE TABLE PROFESSOR (
 Disciplina CHAR(8) NOT NULL,
 Turma CHAR(3) NOT NULL,
 Ano_Sem CHAR(6) NOT NULL,
 Professor VARCHAR(60) NOT NULL,
 Vagas NUMERIC(3)
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (Disciplina,Turma,Ano_Sem);


CREATE TABLE ALUNO (
 Matricula NUMERIC(8) NOT NULL,
 Nome VARCHAR(60) NOT NULL,
 Sexo CHAR(1) NOT NULL,
 Idade NUMERIC(3) NOT NULL,
 Curso CHAR(4) NOT NULL
);

ALTER TABLE ALUNO ADD CONSTRAINT PK_ALUNO PRIMARY KEY (Matricula);


CREATE TABLE HISTORICO (
 Matricula NUMERIC(8) NOT NULL,
 Disciplina CHAR(8) NOT NULL,
 Turma CHAR(3) NOT NULL,
 Ano_Sem CHAR(6) NOT NULL,
 Nota NUMERIC(3,1) NOT NULL
);

ALTER TABLE HISTORICO ADD CONSTRAINT PK_HISTORICO PRIMARY KEY (Matricula,Disciplina,Turma,Ano_Sem);


ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_0 FOREIGN KEY (Curso) REFERENCES CURSO (Curso);


ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_0 FOREIGN KEY (Disciplina) REFERENCES DISCIPLINA (Disciplina);


ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_0 FOREIGN KEY (Curso) REFERENCES CURSO (Curso);


ALTER TABLE HISTORICO ADD CONSTRAINT FK_HISTORICO_0 FOREIGN KEY (Matricula) REFERENCES ALUNO (Matricula);
ALTER TABLE HISTORICO ADD CONSTRAINT FK_HISTORICO_1 FOREIGN KEY (Disciplina,Turma,Ano_Sem) REFERENCES PROFESSOR (Disciplina,Turma,Ano_Sem);


