-- Banco de Dados I
-- Por Duncan Ruiz
--
-- Este arquivo contem a criacao das tabelas para as praticas com SQL.
--
-- Versao 2023/2
--

CREATE TABLE CURSOS (
 Codigo CHAR(5) NOT NULL,
 Titulo VARCHAR(120) NOT NULL
);
ALTER TABLE CURSOS ADD CONSTRAINT PK_CURSOS PRIMARY KEY (Codigo);

CREATE TABLE DISCIPLINAS (
 Codicred CHAR(8) NOT NULL,
 Denominacao VARCHAR(120) NOT NULL
);
ALTER TABLE DISCIPLINAS ADD CONSTRAINT PK_DISCIPLINAS PRIMARY KEY (Codicred);

CREATE TABLE NIVEIS (
 Codicred CHAR(8) NOT NULL,
 Codigo CHAR(5) NOT NULL,
 Nivel NUMERIC(2) NOT NULL CHECK (Nivel > 0 AND Nivel < 13) -- Restrição(if)
);
ALTER TABLE NIVEIS ADD CONSTRAINT PK_NIVEIS PRIMARY KEY (Codicred,Codigo);

CREATE TABLE TURMAS (
 Codicred CHAR(8) NOT NULL,
 Turma NUMERIC(3) NOT NULL CHECK ((Turma > 9 AND Turma < 40 ) OR Turma = 690),
 Ano_Semestre CHAR(6) NOT NULL,
 Horarios VARCHAR(10) NOT NULL,
 Sala VARCHAR(50) NOT NULL,
 Professor VARCHAR(120) NOT NULL
);
ALTER TABLE TURMAS ADD CONSTRAINT PK_TURMAS PRIMARY KEY (Codicred,Turma,Ano_Semestre);

CREATE TABLE ALUNOS (
 Matricula NUMERIC(9) NOT NULL,
 Nome VARCHAR(120) NOT NULL,
 Sexo CHAR(1) NOT NULL CHECK (Sexo IN ('m','f','M','F')),
 Idade NUMERIC(3) NOT NULL,
 Endereco VARCHAR(200),
 Data_Ingresso DATE,
 Curso CHAR(5)
);
ALTER TABLE ALUNOS ADD CONSTRAINT PK_ALUNOS PRIMARY KEY (Matricula);

CREATE TABLE HISTORICO (
 Matricula NUMERIC(9) NOT NULL,
 Codicred CHAR(8) NOT NULL,
 Turma NUMERIC(3) NOT NULL,
 Ano_Semestre CHAR(6) NOT NULL,
 Situacao VARCHAR(20) NOT NULL CHECK (Situacao IN ('Aprovado','Reprovado','Ativo','Cancelado')),
 Nota NUMERIC(3,1) CHECK (Nota IS NULL OR Nota <= 10.0),
 Frequencia NUMERIC(4),
 CHECK ((Ano_Semestre = '2023/2' AND Nota IS NULL and Frequencia IS NOT NULL) OR
        (Ano_Semestre < '2023/2' AND Nota IS NOT NULL and Frequencia IS NULL))
);

ALTER TABLE HISTORICO ADD CONSTRAINT PK_HISTORICO PRIMARY KEY (Matricula,Codicred,Turma,Ano_Semestre);

ALTER TABLE NIVEIS ADD CONSTRAINT FK_NIVEIS_DISCIPLINAS FOREIGN KEY (Codicred) REFERENCES DISCIPLINAS (Codicred);
ALTER TABLE NIVEIS ADD CONSTRAINT FK_NIVEIS_CURSOS FOREIGN KEY (Codigo) REFERENCES CURSOS (Codigo);
ALTER TABLE TURMAS ADD CONSTRAINT FK_TURMAS_DISCIPLINAS FOREIGN KEY (Codicred) REFERENCES DISCIPLINAS (Codicred);
ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_CURSOS FOREIGN KEY (Curso) REFERENCES CURSOS (Codigo);
ALTER TABLE HISTORICO ADD CONSTRAINT FK_HISTORICO_ALUNOS FOREIGN KEY (Matricula) REFERENCES ALUNOS (Matricula);
ALTER TABLE HISTORICO ADD CONSTRAINT FK_HISTORICO_TURMAS FOREIGN KEY (Codicred,Turma,Ano_Semestre) REFERENCES TURMAS (Codicred,Turma,Ano_Semestre);

